from django.urls import path
from . import views


from .views import stopwatch_view
from .views import clock_view, todo_view, toggle_todo


urlpatterns = [
    path('todo/', todo_view, name='todo'),
    path('todo/toggle/<int:todo_id>/', toggle_todo, name='toggle_todo'),
    
    path('clock/', clock_view, name='clock'),
    path('stopwatch/', stopwatch_view, name='stopwatch'),    
    #path('', views.index, name='index'),
    path('carousel_b/', views.carousel_b, name='carousel_b'),
    path('carousel_256/', views.carousel_256, name='carousel_256'),
    path('carousel_128/', views.carousel_128, name='carousel_128'),
    path('carousel_64/', views.carousel_64, name='carousel_64'),
    path('carousel_32/', views.carousel_32, name='carousel_32'),
    path('carousel_16/', views.carousel_16, name='carousel_16'),
    path('carousel_8/', views.carousel_8, name='carousel_8'),
    path('carousel_lite/', views.carousel_lite, name='carousel_lite'),
    path('calculator/', views.calculator, name='calculator'),
    path('unicode/', views.unicode, name='unicode'),

    path('blank5/', views.blank5, name='blank5'),
    path('blank6/', views.blank6, name='blank6'),
    path('blank7/', views.blank7, name='blank7'),
    path('blank8/', views.blank8, name='blank8'),
    path('blank9/', views.blank9, name='blank9'),
    path('blank10/', views.blank10, name='blank10'),
    path('blank11/', views.blank11, name='blank11'),
    path('blank12/', views.blank12, name='blank12'),
    path('blank13/', views.blank13, name='blank13'),
    path('blank14/', views.blank14, name='blank14'),
    path('blank15/', views.blank15, name='blank15'),
    path('yt_000001/', views.yt_000001, name='yt_000001'),
    path('album/', views.album, name='album'),
    path('album_rtl/', views.album_rtl, name='album_rtl'),
    path('badges/', views.badges, name='badges'),
    path('blog/', views.blog, name='blog'),
    path('blog_rtl/', views.blog_rtl, name='blog_rtl'),
    path('breadcrumbs/', views.breadcrumbs, name='breadcrumbs'),
    path('buttons/', views.buttons, name='buttons'),
    path('carousel/', views.carousel, name='carousel'),
    path('carousel_rtl/', views.carousel_rtl, name='carousel_rtl'),
    path('cheatsheet/', views.cheatsheet, name='cheatsheet'),
    path('cheatsheet_rtl/', views.cheatsheet_rtl, name='cheatsheet_rtl'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout_rtl/', views.checkout_rtl, name='checkout_rtl'),
    path('cover/', views.cover, name='cover'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard_rtl/', views.dashboard_rtl, name='dashboard_rtl'),
    path('dropdowns/', views.dropdowns, name='dropdowns'),
    path('features/', views.features, name='features'),
    path('footers/', views.footers, name='footers'),
    path('grid/', views.grid, name='grid'),
    path('headers/', views.headers, name='headers'),
    path('heroes/', views.heroes, name='heroes'),
    path('jumbotron/', views.jumbotron, name='jumbotron'),
    path('jumbotrons/', views.jumbotrons, name='jumbotrons'),
    path('list_groups', views.list_groups, name='list_groups'),
    path('masonry/', views.masonry, name='masonry'),
    path('modals/', views.modals, name='modals'),
    path('navbar_bottom/', views.navbar_bottom, name='navbar_bottom'),
    path('navbar_fixed/', views.navbar_fixed, name='navbar_fixed'),
    path('navbars/', views.navbars, name='navbars'),
    path('navbars_offcanvas/', views.navbars_offcanvas, name='navbars_offcanvas'),
    path('navbar_static/', views.navbar_static, name='navbar_static'),
    path('offcanvas/', views.offcanvas, name='offcanvas'),
    path('offcanvas_navbar/', views.offcanvas_navbar, name='offcanvas_navbar'),
    path('pricing/', views.pricing, name='pricing'),
    path('product/', views.product, name='product'),
    path('sidebars/', views.sidebars, name='sidebars'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('starter_template/', views.starter_template, name='starter_template'),
    path('sticky_footer/', views.sticky_footer, name='sticky_footer'),
    path('sticky_footer_navbar/', views.sticky_footer_navbar, name='sticky_footer_navbar'),
    path('picker/', views.picker, name='picker'),
    #path('color_grid/', views.color_grid, name='color_grid'),
    path('color_grid/', views.color_input, name='color_input'),

    path('trig/', views.trig_calculator, name='trig'),

    path('generator/', views.generate_password, name='generator'),
]